name: Jekyll GitHub Pages with Flask

on:
  push:
    branches:
      - main  # or specify the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask Werkzeug

      - name: Run Flask app
        run: |
          flask run
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
